"""
Project Euler Problem 2
=======================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""

from itertools import takewhile, islice
from typing import Iterator

def fib(n: int, m: int) -> Iterator[int]:
    yield n
    yield m
    while True:
        p = n + m
        n = m
        m = p
        yield p

print(sum((i for i in takewhile(lambda x: x < 4000000, fib(1,2)) if i%2 == 0)))
